name: itunes_music_player
description: A project for playing song.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # C
  cupertino_icons: ^1.0.2
  # G
  get_it: ^7.5.0
  google_fonts: ^4.0.4
  # H
  http: ^0.13.6
  # I
  intl: ^0.17.0
  injectable: ^2.1.1
  # J
  just_audio: ^0.9.32
  # P
  provider: ^6.0.5
  # S
  shared_preferences: ^2.1.0
  # T
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # B
  build_runner: ^2.3.3
  # F
  flutter_lints: ^2.0.0
  # I
  injectable_generator: ^2.1.5

flutter:
  # generate: true # disable when generate build_runner
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
